language: node_js
node_js:
  - "7"
  - "8"

notifications:
  email:
    on_success: never
    on_failure: change

  slack:
    on_success: change
    rooms:
    - secure: eiw6pYznqklbo1ou7Wq7OI+ZB0QKUOTnYr/Q8Heke5EpHblXrvby2LdTpyb6e+1gzUJsuzI56Iq4gq40izspPBgOJpdtOAqijtqSVsdnM3Mxwhh4u4btzZGaPJM3YNSlVAH1IfUaobduLY/CghEKASvSIWvEhA6EcCjnG7/vLO6G7EEW/S4um2msS77ny+YO0kwh90nw8G6RAwccm0+WD9/GE+TElbpiXaScusVnRtoFflTSMvmw78wsQgnEu4C/0et94iPEXxDD5+a2uIPJAx4ZdWdyP07EKpUQ4QmmlfrOI76kwREpGEWuUaCvqigkHow9Fx+f7hHnJgNIovkY6cZPNuc50nIroPRwUQGFvut6vrM7a1nJ7zOx3c3pmh4ffSJTuSYp3p72oLFI77fZXOHTqEst4fb2KoEnE4lqZGlhgX8qDlFp4GVM8OS/ZpI4hIdCHZyP6nf++XxH628DnnYfgJvLq5KoTA3MJg5ltAG1FYEoBreTdNA6lGpPZLNs8LQbwGTulD6f3svxf925rWS56S24u7yvNXkyxEPLIx+1CVLxaZyeyH3H39Iy0lkeyZl2qQ77wK13qZe5vhpO6w9cWyatDRgznSQgfeuX8Zj33WNlhueNj2jbpeCFldcsx5eQP9gbehWySkfqBhP/1iKgB9ydaqlKJpFc8Um8IWs=

services:
  - postgresql

before_script:
  - 'createdb real-time-server-test'
  - 'cp .env.example .env'

git:
  depth: 10
