language: node_js
node_js: 'node'
notifications:
  email:
    on_success: never
    on_failure: change
services:
  - postgresql
before_script:
  - 'createdb real-time-server-test'
  - 'cp .env.example .env'
